version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      PIP_CACHE_DIR: ~/.cache/pip

# ---------------------------------------
# JOB 1: Install + Lint
# ---------------------------------------
jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install linting tools
          command: |
            python -m pip install --upgrade pip
            pip install black flake8
      - run:
          name: Run black formatter check
          command: black --check .
      - run:
          name: Run flake8 lint check
          command: flake8 .

# ---------------------------------------
# JOB 2: Run Unit Tests
# ---------------------------------------
  test:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}
            - deps-
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests with pytest
          command: pytest -q --disable-warnings
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

# ---------------------------------------
# JOB 3: Train ML Model
# ---------------------------------------
  train:
    executor: python-executor
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run training script
          command: |
            mkdir -p models
            python src/train_model.py
      - persist_to_workspace:
          root: .
          paths:
            - models/
      - store_artifacts:
          path: models/
          destination: trained_models

# ---------------------------------------
# JOB 4: Build & Push Docker Image
# ---------------------------------------
  docker_build:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Copy model files
          command: |
            mkdir -p models
            cp -r /workspace/models ./models || echo "No models found."
      - run:
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t ${DOCKERHUB_USER}/ml-app:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image
          command: |
            docker push ${DOCKERHUB_USER}/ml-app:${CIRCLE_SHA1}
      - store_artifacts:
          path: models/
          destination: docker_build_models

# ---------------------------------------
# WORKFLOW: Pipeline Order
# ---------------------------------------
workflows:
  version: 2
  build_train_deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - train:
          requires:
            - test
      - docker_build:
          requires:
            - train
